from . import res_partner
from . import res_company
from . import res_config_settings
from . import limousine_pricing
from . import limousine_pricing_line
from . import limousine_fines_config
from . import limousine_contract
from . import limousine_contract_timesheet
from . import account_payment
